version: "3.11"

services:
  fastapi_database:
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"